// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","layout":false,"id":"1"},"2":{"path":"/login","layout":false,"id":"2"},"3":{"path":"/personInfo","parentId":"@@/global-layout","id":"3"},"4":{"path":"/whitelist","parentId":"@@/global-layout","id":"4"},"5":{"path":"/*","parentId":"@@/global-layout","id":"5"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.jsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.jsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__PersonInfo__index" */'@/pages/PersonInfo/index.jsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__SystemConfig__WhiteList__index" */'@/pages/SystemConfig/WhiteList/index.jsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__404__index" */'@/pages/404/index.jsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/yubowen/Desktop/pqc-cli/aaaa/layouts/index.jsx')),
},
  };
}
