name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Read package.json
      id: package
      run: |
        echo "::set-output name=version::v$(jq -r .version package.json)"
        echo "::set-output name=commit_message::$(git log --format=%B -n 1 $GITHUB_SHA)"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.package.outputs.version }}
        release_name: ${{ steps.package.outputs.version }}
        body: ${{ steps.package.outputs.commit_message }}
