name: GitHub Release

on:
  release:
    types: [created]
  push:
    branches:
      - main


jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
          with:
            token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
            release-type: node
            package-name: standard-version